# Generated by Django 6.0.4 on 2026-04-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('publish_date', models.DateField()),
                ('author', models.CharField(max_length=150)),
                ('price', models.FloatField()),
            ],
        ),
    ]
